version: "3"

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "3000:3000"
 
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - express-app
  