version: "3"

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "3000:3000"
    networks:
      - my_network
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - express-app
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge